export { default as Home } from './Home'
export { default as Releases } from './Releases'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as ReleaseDetail } from './ReleaseDetail'
export { ApiTest } from './ApiTest'